trigger:
- main

pool: DevOps project Pool

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
    vite build
  displayName: 'npm install and build'
- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'dist'
    downloadPath: '$(System.ArtifactsDirectory)'
# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: 'dist'
#     ArtifactName: 'drop'
#     publishLocation: 'Container'