trigger:
- main

pool: DevOps project Pool
variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'docker'
        repository: 'cyberrizzler/frontend'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'